################################################################## BEGIN CLASS
##########################
# Interfaces
# eq_equation()
##########################

# Subclasses of `eq_equation` should include the following:
# 1. convert2latex.__subclass__()
#    that converts the subclass to a latex-friendly string
# 2. as.character.__subclass__() method
#    that wraps convert2latex.__subclass__()

##########################
# Class Definition
# eq_equation()
##########################
# This is a class script.
# It contains a single class, its methods, and utility functions.

########## Full Constructor / Helper
# No low-level constructor or validator included.

#' @title
#' Build an \code{equatiomatic} equation.
#'
#' @description
#' Final equation generated by \code{equatiomatic} from a model.
#'
#' @details
#' The final equation object produced by \code{equatiomatic} from a model.
#'
#' @keywords internal
#'
#' @param ... One or more R objects convertible to a character, including `eq_line`.
#' @param .wrapable_operators A character vector. Represents the character
#'   objects where the equation can be wrapped. Default is \code{c("=", "+", "-")}.
#' @param .special_class A character. A class, preferably the model class
#'   prefixed with \dQuote{eq_}, that will be used for dispatch. Useful when
#'   special wrapping or alignment functions are required.
#'
#' @return A list classed as `eq_equation` or a special class as provided.
#'
#' @family term constructors
#' @family creating equations
#' @family extensibility functions
#'
#' @examples
#' eq_equation(c_term("y0"), "=", myterm1, "+", myterm2)
#'
#' @export
eq_equation <-
  function(
    ...,
    .wrapable_operators = c("=", "+", "-"),
    .special_class = NA_character_
  ) {
    # An equation is a line that may contains lines.
    # Must pass ... and not dots.
    eq <- eq_line(..., .wrapable_operators = .wrapable_operators)

    # Lines are wrapable by their nature
    line_objs <- vapply(eq$terms, function(x) { inherits(x, "eq_line") }, logical(1))
    eq[["wrapable"]][line_objs] <- TRUE

    # Set Class and Attributes
    class(eq) <-
      if(!is.na(.special_class) ) {
        c(.special_class, "eq_equation", "term_obj")
      } else {
        c("eq_equation", "term_obj")
      }

    attributes(eq)[["flatten"]] <- FALSE

    # Return
    eq
  }

##########################
# Methods
##########################

################
# Equatiomatic (see defaults.R)
################

########## convert2latex & wrapper (as.eq_term)
#' @title
#' Convert `eq_equation` object to Latex
#'
#' @description
#' Converts a `eq_equation` classed object latex-friendly character string.
#'
#' @keywords internal
#'
#' @inherit convert2latex.eq_line
#' @param align_env One of \code{c("aligned", "aligned*", "align", "align*")}.
#'   TeX environment to wrap around equation. Default is \code{aligned}
#'
#'
#' @return A latex-friendly character (string) representation of the term.
#'
#' @family convert2latex functions
#'
#' @export
convert2latex.eq_equation <-
  function(
    .x,
    .use_coef = FALSE,
    .coef_digits = 2,
    .use_coef_sign = TRUE,
    .inverse_sign = FALSE,
    .wrap = FALSE,
    .operator_location = "end",
    .terms_per_line = 4,
    .align_env = "aligned",
    ...
  ) {
    # Type Checks
    # TODO: Add type checks

    # Convert to characters
    chrs <-
      suppressWarnings(
        lapply(
          .x$terms,
          convert2latex,
          .use_coef = .use_coef,
          .coef_digits = .coef_digits,
          .use_coef_sign = .use_coef_sign,
          .inverse_sign = .inverse_sign,
          .wrap = .wrap,
          .operator_location = .operator_location,
          .terms_per_line = .terms_per_line
        )
      )

    # Wrapping
    if(.wrap) {
      chrs <-
        wrap_eq(
          .x = .x,
          .chrs = chrs,
          .terms_per_line = .terms_per_line,
          .operator_location = .operator_location
        )
    }

    # Alignment
    chrs <-
      align_eq(
        .chrs = chrs,
        .align_env = .align_env
      )

    # Return
    paste0(chrs, collapse = " ")
  }


################
# Base R
################

########## as.character

#' @rdname convert2latex.eq_equation
#' @method as.character eq_equation
#' @export
as.character.eq_equation <-
  function(
    .x,
    ...
  ) {
    convert2latex(.x = .x, ...)
  }

################
# External Packages
################
# Use function names as they come from the source package.
# Use ... to pass through properties.

# None


##########################
# Utility Functions
##########################
# These functions are used on this class and are not
# expected to be used elsewhere or with method dispatch.

# None

################################################################## END CLASS
